[workspace]
authors = ["lkless <leakless21@gmail.com>"]
channels = ["conda-forge"]
name = "vits-tts-vietnamese"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
lint = "ruff check . && black --check ."

[dependencies]
python = "<3.13"
loguru = ">=0.7.3,<0.8"
gunicorn = ">=21.2.0,<22"
black = ">=24.0.0,<25"
ruff = ">=0.5.0,<0.6"
pip = ">=24.0,<25"

[pypi-dependencies]
tornado = ">=6.5.2, <7"
onnxruntime = ">=1.22.1, <2"
piper-phonemize = ">=1.1.0, <2"
jsonschema = ">=4.25.1, <5"
requests = ">=2.32.5, <3"
piper-tts = ">=1.3.0, <2"
pyyaml = ">=6.0, <7"
cachetools = ">=5.3.0, <6"
