[workspace]
authors = ["lkless <leakless21@gmail.com>"]
channels = ["conda-forge"]
name = "vits-tts-vietnamese"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "<3.13"

[pypi-dependencies]
tornado = ">=6.5.2, <7"
onnxruntime = ">=1.22.1, <2"
piper-phonemize = ">=1.1.0, <2"
jsonschema = ">=4.25.1, <5"
