server:
  port: 8888

tts:
  #model_path: "models/infore/vi_VN-vais1000-medium.onnx"
  #config_path: "models/infore/vi_VN-vais1000-medium.onnx.json"
  model_path: "models/v2/finetuning_pretrained_vi.onnx"
  config_path: "models/v2/finetuning_pretrained_vi.onnx.json"
  audio_output_dir: "audio/"
  cache_size: 100
  default_speed: "normal"
  noise_scale: 0.4
  noise_w: 0.5

logging:
  level: "INFO"
  file: "logs/tts_server.log"
  max_file_size: "10MB"
  backup_count: 5
  format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"

debug:
  enabled: false
  log_performance: false
  log_function_calls: false
